services:
  overlaydb:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ${MOUNT_POSTGRES_DATA:-./data/postgres}:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
  overlay-serv:
    image: ghcr.io/nils-witt/tileserve-go
    ports:
      - "8085:80"
    environment:
      DATABASE_URL: postgres://user:pass@overlaydb:5432/db?sslmode=disable
    volumes:
      - ${MOUNT_OSM_OVERLAYS:-./data/overlays}:/data
    depends_on:
      overlaydb:
        condition: service_healthy
