package handler

import (
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"

	"github.com/google/uuid"

	"nilswitt.dev/tileserve-go/internal/store"
	"nilswitt.dev/tileserve-go/internal/tilearchive"
)

// maxUploadSize caps the size of an uploaded map version archive.
const maxUploadSize = 1 << 30 // 1 GiB

// uploadMapVersionHandler accepts a zip or tar (optionally gzip-compressed)
// archive as the raw request body, extracts it, and atomically bumps the
// map's current_version. Extraction happens into a staging directory next to
// the map's final location first; the DB version is only reserved (and the
// directory put in place) once extraction fully succeeds, so a bad upload
// never leaves the map pointing at a broken version.
func uploadMapVersionHandler(st *store.Store, dataRoot string, id uuid.UUID) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !requireMethod(w, r, http.MethodPost) {
			return
		}

		if !requireMapPermission(w, r, st, id,
			func(p store.Permissions) bool { return p.CanCreate },
			func(mp store.MapPermission) bool { return mp.CanEdit },
		) {
			return
		}

		tmpPath, ok := receiveUpload(w, r)
		if !ok {
			return
		}
		defer func() { _ = os.Remove(tmpPath) }()

		dir := tilearchive.MapDir(dataRoot, id)

		stagingDir, ok := extractUploadedArchive(w, tmpPath, dir)
		if !ok {
			return
		}
		//nolint:gosec // G703: stagingDir is server-generated by tilearchive.ExtractArchive (os.MkdirTemp under dir), never derived from request input
		defer func() { _ = os.RemoveAll(stagingDir) }()

		if err := tilearchive.WriteTileIndex(stagingDir); err != nil {
			http.Error(w, "failed to build tile index", http.StatusInternalServerError)
			return
		}

		m, err := st.IncrementMapVersion(r.Context(), id, usernameFromContext(r.Context()))
		if err != nil {
			writeStoreError(w, err, store.ErrMapNotFound, http.StatusNotFound, "map not found", "failed to record new version")
			return
		}

		destDir := filepath.Join(dir, m.CurrentVersion)
		//nolint:gosec // G703: both stagingDir (see above) and destDir (dir joined with a version number this handler just reserved via IncrementMapVersion) are server-generated, never derived from request input
		if err := os.Rename(stagingDir, destDir); err != nil {
			http.Error(w, "failed to store version", http.StatusInternalServerError)
			return
		}

		recordAudit(r, st, "upload", "map_version", id.String()+":"+m.CurrentVersion, "")

		writeJSON(w, http.StatusCreated, m)
	}
}

// receiveUpload buffers r's body (capped at maxUploadSize) into a closed
// temp file and returns its path. On success the caller is responsible for
// removing it; on failure receiveUpload has already written the appropriate
// error response and cleaned up.
func receiveUpload(w http.ResponseWriter, r *http.Request) (string, bool) {
	r.Body = http.MaxBytesReader(w, r.Body, maxUploadSize)

	tmpFile, err := os.CreateTemp("", "tileserve-upload-*")
	if err != nil {
		http.Error(w, "failed to buffer upload", http.StatusInternalServerError)
		return "", false
	}
	defer func() { _ = tmpFile.Close() }()

	if _, err := io.Copy(tmpFile, r.Body); err != nil {
		_ = os.Remove(tmpFile.Name())

		if _, ok := errors.AsType[*http.MaxBytesError](err); ok {
			http.Error(w, "upload too large", http.StatusRequestEntityTooLarge)
			return "", false
		}

		http.Error(w, "failed to read upload", http.StatusBadRequest)

		return "", false
	}

	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpFile.Name())

		http.Error(w, "failed to buffer upload", http.StatusInternalServerError)

		return "", false
	}

	return tmpFile.Name(), true
}

// extractUploadedArchive extracts tmpPath into a fresh staging directory
// under dir via tilearchive.ExtractArchive, translating any error into the
// appropriate HTTP response. On success the caller is responsible for
// removing the returned staging directory; on failure extractUploadedArchive
// has already written the appropriate error response and cleaned up.
func extractUploadedArchive(w http.ResponseWriter, tmpPath, dir string) (string, bool) {
	stagingDir, err := tilearchive.ExtractArchive(tmpPath, dir)
	if err == nil {
		return stagingDir, true
	}

	switch {
	case errors.Is(err, tilearchive.ErrUnsupportedFormat):
		http.Error(w, err.Error(), http.StatusBadRequest)
	case errors.Is(err, tilearchive.ErrInvalidArchive):
		http.Error(w, err.Error(), http.StatusBadRequest)
	default:
		http.Error(w, "failed to extract archive", http.StatusInternalServerError)
	}

	return "", false
}
